2021-06-22 07:38:35.758 [error] <0.401.0>@Elixir.AMQP.Application:get_channel CRASH REPORT Process <0.401.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.AMQP.Application':get_channel(readings) in application_master:init/4 line 142
2021-06-22 07:39:46.866 [error] <0.348.0>@Elixir.AMQP.Application:get_channel CRASH REPORT Process <0.348.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.AMQP.Application':get_channel(readings) in application_master:init/4 line 142
2021-06-22 08:17:57.839 [error] <0.371.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.HVACDatabase.Pubsub.RabbitMQ',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,...}]}} in context start_error
2021-06-22 08:17:57.840 [error] <0.369.0> CRASH REPORT Process <0.369.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{'EXIT',{undef,[{'Elixir.HVACDatabase.Pubsub.RabbitMQ',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,...},...]}}}},...} in application_master:init/4 line 142
2021-06-22 08:20:38.691 [error] <0.387.0>@Elixir.AMQP.Connection:open:29 CRASH REPORT Process <0.387.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Connection':open(nil) line 29
2021-06-22 08:21:03.797 [error] <0.387.0>@Elixir.AMQP.Connection:open:29 CRASH REPORT Process <0.387.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Connection':open(nil) line 29
2021-06-22 08:22:14.533 [error] <0.482.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25 in context start_error
2021-06-22 08:22:14.533 [error] <0.497.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 CRASH REPORT Process <0.497.0> with 0 neighbours crashed with reason: no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25
2021-06-22 08:22:14.533 [error] <0.480.0> CRASH REPORT Process <0.480.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{{badmatch,{error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}}},[{'Elixir.HVACDatabase.Pubsub.RabbitMQ',setup_queue,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,25}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',init,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',init,1,[{file,"lib/publisher...."},...]},...]}}},...} in application_master:init/4 line 142
2021-06-22 08:25:17.559 [error] <0.482.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'readings' in vhost '/': received 'true' but current is 'false'">>}},{gen_server,call,[<0.513.0>,{call,{'queue.declare',0,<<"readings">>,false,true,false,false,false,[]},none,<0.497.0>},70000]}} in context start_error
2021-06-22 08:28:13.921 [error] <0.2609.0>@Elixir.AMQP.Queue:bind Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason call to undefined function 'Elixir.AMQP.Queue':bind(#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.2629.0>},...}, <<"readings">>) in context start_error
2021-06-22 08:28:13.922 [error] <0.2624.0>@Elixir.AMQP.Queue:bind CRASH REPORT Process <0.2624.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.AMQP.Queue':bind(#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.2629.0>},...}, <<"readings">>)
2021-06-22 08:28:13.923 [error] <0.2607.0> CRASH REPORT Process <0.2607.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{undef,[{'Elixir.AMQP.Queue',bind,[#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.2629.0>},custom_consumer => nil,pid => <0.2638.0>},<<"readings">>],[]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',setup_queue,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,33}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',init,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,11}]},...]}}},...} in application_master:init/4 line 142
2021-06-22 08:29:46.264 [error] <0.405.0> CRASH REPORT Process <0.405.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :name option to be one of the following:\n\n  * nil\n  * atom\n  * {:global, term}\n  * {:via, module, term}\n\nGot: {:via, Registry, Registry.DeviceRegistry, \"us1\"}\n">>} in 'Elixir.GenServer':do_start/4 line 947 in application_master:init/4 line 142
2021-06-22 08:29:46.278 [error] <0.419.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.419.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 08:29:46.278 [error] <0.416.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.416.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.418.0>, {<<"client 127.0.0.1:58394 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.419.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 08:30:32.446 [error] <0.403.0>@Elixir.Registry.DeviceRegistry:whereis_name CRASH REPORT Process <0.403.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Registry.DeviceRegistry':whereis_name(<<"us1">>) in application_master:init/4 line 142
2021-06-22 08:31:36.974 [error] <0.408.0>@Elixir.DeviceRegistry:whereis_name CRASH REPORT Process <0.408.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.DeviceRegistry':whereis_name(<<"us1">>) in application_master:init/4 line 142
2021-06-22 08:35:27.294 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.DeviceRegistry">>} in 'Elixir.Registry':'key_info!'/1 line 1276 in application_master:init/4 line 142
2021-06-22 08:35:27.310 [error] <0.416.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.416.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 08:35:27.310 [error] <0.413.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.413.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.415.0>, {<<"client 127.0.0.1:55307 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.416.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 08:40:25.996 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.DeviceRegistry">>} in 'Elixir.Registry':'key_info!'/1 line 1276 in application_master:init/4 line 142
2021-06-22 08:40:26.011 [error] <0.416.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.416.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 08:40:26.011 [error] <0.413.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.413.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.415.0>, {<<"client 127.0.0.1:54850 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.416.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 08:42:19.521 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Registry.DeviceRegistry">>} in 'Elixir.Registry':'key_info!'/1 line 1276 in application_master:init/4 line 142
2021-06-22 08:42:19.533 [error] <0.416.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.416.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 08:42:19.533 [error] <0.413.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.413.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.415.0>, {<<"client 127.0.0.1:52204 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.416.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:02:16.414 [error] <0.436.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.436.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:02:16.414 [error] <0.433.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.433.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.435.0>, {<<"client 127.0.0.1:54573 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.436.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:02:16.414 [error] <0.433.0> Supervisor {<0.433.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.435.0>, {<<"client 127.0.0.1:54573 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.436.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:02:16.429 [error] <0.384.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.399.0> exit with reason {shutdown,{gen_server,call,[<0.435.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.399.0>},70000]}} in context child_terminated
2021-06-22 09:02:16.469 [error] <0.464.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.464.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:02:16.470 [error] <0.461.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.461.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.463.0>, {<<"client 127.0.0.1:54575 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.464.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:02:16.470 [error] <0.461.0> Supervisor {<0.461.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.463.0>, {<<"client 127.0.0.1:54575 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.464.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:02:16.470 [error] <0.384.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.437.0> exit with reason {shutdown,{gen_server,call,[<0.463.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.437.0>},70000]}} in context child_terminated
2021-06-22 09:02:16.503 [error] <0.491.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:02:16.504 [error] <0.488.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.488.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.490.0>, {<<"client 127.0.0.1:54577 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.491.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:02:16.504 [error] <0.488.0> Supervisor {<0.488.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.490.0>, {<<"client 127.0.0.1:54577 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.491.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:02:16.505 [error] <0.384.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.465.0> exit with reason {shutdown,{gen_server,call,[<0.490.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.465.0>},70000]}} in context child_terminated
2021-06-22 09:02:16.534 [error] <0.518.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.518.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:02:16.535 [error] <0.515.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.515.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.517.0>, {<<"client 127.0.0.1:54579 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.518.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:02:16.535 [error] <0.515.0> Supervisor {<0.515.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.517.0>, {<<"client 127.0.0.1:54579 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.518.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:02:16.535 [error] <0.384.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.492.0> exit with reason {shutdown,{gen_server,call,[<0.517.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.492.0>},70000]}} in context child_terminated
2021-06-22 09:02:16.535 [error] <0.384.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.492.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:02:16.560 [error] <0.426.0> CRASH REPORT Process <0.426.0> with 0 neighbours exited with reason: {{shutdown,{'Elixir.DBConnection.Holder',checkout,[<0.387.0>,[{timeout,infinity},{queue,true}]]}},{'Elixir.DBConnection.Holder',checkout,[<0.458.0>,[{log,#Fun<Elixir.Ecto.Adapters.SQL.14.84178060>},{cache_statement,<<"ecto_insert_devices">>},{on_conflict,replace_all},{conflict_target,device_id},{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.Ownership'}]]}} in 'Elixir.DBConnection.Holder':checkout/3 line 95
2021-06-22 09:06:29.375 [error] <0.534.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.534.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:06:29.375 [error] <0.531.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.531.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.533.0>, {<<"client 127.0.0.1:53083 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.534.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:06:29.375 [error] <0.531.0> Supervisor {<0.531.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.533.0>, {<<"client 127.0.0.1:53083 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.534.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:06:29.376 [error] <0.482.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.497.0> exit with reason {shutdown,{gen_server,call,[<0.533.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.497.0>},70000]}} in context child_terminated
2021-06-22 09:06:29.507 [error] <0.562.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.562.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:06:29.507 [error] <0.559.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.559.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.561.0>, {<<"client 127.0.0.1:53085 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.562.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:06:29.507 [error] <0.559.0> Supervisor {<0.559.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.561.0>, {<<"client 127.0.0.1:53085 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.562.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:06:29.507 [error] <0.482.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.535.0> exit with reason {shutdown,{gen_server,call,[<0.561.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.535.0>},70000]}} in context child_terminated
2021-06-22 09:06:29.537 [error] <0.589.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.589.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:06:29.537 [error] <0.586.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.586.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.588.0>, {<<"client 127.0.0.1:53087 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.589.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:06:29.537 [error] <0.586.0> Supervisor {<0.586.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.588.0>, {<<"client 127.0.0.1:53087 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.589.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:06:29.537 [error] <0.482.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.563.0> exit with reason {shutdown,{gen_server,call,[<0.588.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.563.0>},70000]}} in context child_terminated
2021-06-22 09:06:29.568 [error] <0.616.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.616.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:06:29.568 [error] <0.613.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.613.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.615.0>, {<<"client 127.0.0.1:53089 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.616.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:06:29.568 [error] <0.613.0> Supervisor {<0.613.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.615.0>, {<<"client 127.0.0.1:53089 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.616.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:10:13.322 [error] <0.405.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.405.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:10:13.322 [error] <0.402.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.402.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.404.0>, {<<"client 127.0.0.1:51895 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.405.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:10:13.322 [error] <0.402.0> Supervisor {<0.402.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.404.0>, {<<"client 127.0.0.1:51895 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.405.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:10:13.345 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.368.0> exit with reason {shutdown,{gen_server,call,[<0.404.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.368.0>},70000]}} in context child_terminated
2021-06-22 09:10:13.378 [error] <0.433.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.433.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:10:13.378 [error] <0.430.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.430.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.432.0>, {<<"client 127.0.0.1:51897 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.433.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:10:13.378 [error] <0.430.0> Supervisor {<0.430.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.432.0>, {<<"client 127.0.0.1:51897 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.433.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:10:13.378 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.406.0> exit with reason {shutdown,{gen_server,call,[<0.432.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.406.0>},70000]}} in context child_terminated
2021-06-22 09:10:13.403 [error] <0.460.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:10:13.403 [error] <0.457.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:51899 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.460.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:10:13.403 [error] <0.457.0> Supervisor {<0.457.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.459.0>, {<<"client 127.0.0.1:51899 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.460.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:10:13.404 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.434.0> exit with reason {shutdown,{gen_server,call,[<0.459.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.434.0>},70000]}} in context child_terminated
2021-06-22 09:10:13.431 [error] <0.487.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.487.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:10:13.431 [error] <0.484.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.484.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.486.0>, {<<"client 127.0.0.1:51901 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.487.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:10:13.431 [error] <0.484.0> Supervisor {<0.484.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.11>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.486.0>, {<<"client 127.0.0.1:51901 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.487.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:10:13.431 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.461.0> exit with reason {shutdown,{gen_server,call,[<0.486.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.461.0>},70000]}} in context child_terminated
2021-06-22 09:10:13.431 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.461.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:10:13.462 [error] <0.399.0> CRASH REPORT Process <0.399.0> with 0 neighbours exited with reason: {{shutdown,{'Elixir.DBConnection.Holder',checkout,[<0.356.0>,[{timeout,infinity},{queue,true}]]}},{'Elixir.DBConnection.Holder',checkout,[<0.427.0>,[{log,#Fun<Elixir.Ecto.Adapters.SQL.14.84178060>},{cache_statement,<<"ecto_insert_devices">>},{on_conflict,replace_all},{conflict_target,device_id},{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.Ownership'}]]}} in 'Elixir.DBConnection.Holder':checkout/3 line 95
2021-06-22 09:10:13.466 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"could not lookup Ecto repo HVACDatabase.Repo because it was not started or it does not exist">>} in 'Elixir.Ecto.Repo.Registry':lookup/1 line 22
2021-06-22 09:14:07.202 [error] <0.372.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at undefined exit with reason no match of right hand value {error,econnrefused} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25 in context start_error
2021-06-22 09:14:07.203 [error] <0.387.0>@Elixir.HVACDatabase.Pubsub.RabbitMQ:setup_queue:25 CRASH REPORT Process <0.387.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.HVACDatabase.Pubsub.RabbitMQ':setup_queue/0 line 25
2021-06-22 09:14:07.203 [error] <0.370.0> CRASH REPORT Process <0.370.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACDatabase.Pubsub.RabbitMQ',{{badmatch,{error,econnrefused}},[{'Elixir.HVACDatabase.Pubsub.RabbitMQ',setup_queue,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,25}]},{'Elixir.HVACDatabase.Pubsub.RabbitMQ',init,0,[{file,"lib/hvac_database/pubsub/rabbit_mq.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',init,1,[{file,"lib/publisher.ex"},{line,216}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_s..."},...]},...]}}},...} in application_master:init/4 line 142
2021-06-22 09:17:59.593 [error] <0.447.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.447.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:17:59.593 [error] <0.444.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.444.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.446.0>, {<<"client 127.0.0.1:51739 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.447.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:17:59.593 [error] <0.444.0> Supervisor {<0.444.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.446.0>, {<<"client 127.0.0.1:51739 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.447.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:17:59.601 [error] <0.394.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.409.0> exit with reason {shutdown,{gen_server,call,[<0.446.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.409.0>},70000]}} in context child_terminated
2021-06-22 09:17:59.646 [error] <0.474.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.474.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:17:59.647 [error] <0.471.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.471.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.473.0>, {<<"client 127.0.0.1:51741 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.474.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:17:59.647 [error] <0.471.0> Supervisor {<0.471.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.473.0>, {<<"client 127.0.0.1:51741 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.474.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:17:59.647 [error] <0.394.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.448.0> exit with reason {shutdown,{gen_server,call,[<0.473.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.448.0>},70000]}} in context child_terminated
2021-06-22 09:17:59.678 [error] <0.502.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.502.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:17:59.678 [error] <0.499.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.499.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.19>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.501.0>, {<<"client 127.0.0.1:51743 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.502.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:17:59.678 [error] <0.499.0> Supervisor {<0.499.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.19>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.501.0>, {<<"client 127.0.0.1:51743 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.502.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:17:59.678 [error] <0.394.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.475.0> exit with reason {shutdown,{gen_server,call,[<0.501.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.475.0>},70000]}} in context child_terminated
2021-06-22 09:17:59.705 [error] <0.529.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.529.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:17:59.706 [error] <0.526.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.526.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.21>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.528.0>, {<<"client 127.0.0.1:51745 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.529.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:17:59.706 [error] <0.526.0> Supervisor {<0.526.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.21>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.528.0>, {<<"client 127.0.0.1:51745 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.529.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:17:59.706 [error] <0.394.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.503.0> exit with reason {shutdown,{gen_server,call,[<0.528.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.503.0>},70000]}} in context child_terminated
2021-06-22 09:17:59.706 [error] <0.394.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.503.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:17:59.732 [error] <0.437.0> CRASH REPORT Process <0.437.0> with 0 neighbours exited with reason: {{shutdown,{'Elixir.DBConnection.Holder',checkout,[<0.397.0>,[{timeout,infinity},{queue,true}]]}},{'Elixir.DBConnection.Holder',checkout,[<0.489.0>,[{log,#Fun<Elixir.Ecto.Adapters.SQL.14.84178060>},{cache_statement,<<"ecto_insert_devices">>},{on_conflict,replace_all},{conflict_target,device_id},{timeout,15000},{pool_size,10},{pool,'Elixir.DBConnection.Ownership'}]]}} in 'Elixir.DBConnection.Holder':checkout/3 line 95
2021-06-22 09:17:59.736 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"could not lookup Ecto repo HVACDatabase.Repo because it was not started or it does not exist">>} in 'Elixir.Ecto.Repo.Registry':lookup/1 line 22
2021-06-22 09:19:37.217 [error] <0.407.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.407.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:19:37.217 [error] <0.404.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.404.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.406.0>, {<<"client 127.0.0.1:49619 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.407.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:19:37.217 [error] <0.404.0> Supervisor {<0.404.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.15>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.406.0>, {<<"client 127.0.0.1:49619 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.407.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:19:37.246 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.368.0> exit with reason {shutdown,{gen_server,call,[<0.406.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.368.0>},70000]}} in context child_terminated
2021-06-22 09:19:37.284 [error] <0.435.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.435.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:19:37.284 [error] <0.432.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.432.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.434.0>, {<<"client 127.0.0.1:49621 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.435.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:19:37.284 [error] <0.432.0> Supervisor {<0.432.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.434.0>, {<<"client 127.0.0.1:49621 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.435.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:19:37.284 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.408.0> exit with reason {shutdown,{gen_server,call,[<0.434.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.408.0>},70000]}} in context child_terminated
2021-06-22 09:19:37.310 [error] <0.401.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.401.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.401.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:19:37.320 [error] <0.464.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.464.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:19:37.320 [error] <0.461.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.461.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.19>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.463.0>, {<<"client 127.0.0.1:49623 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.464.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2021-06-22 09:19:37.320 [error] <0.461.0> Supervisor {<0.461.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.19>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.463.0>, {<<"client 127.0.0.1:49623 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.464.0> exit with reason reached_max_restart_intensity in context shutdown
2021-06-22 09:19:37.320 [error] <0.457.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.457.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.457.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:19:37.320 [error] <0.353.0> Supervisor 'Elixir.HVACDatabase.Supervisor' had child 'Elixir.HVACDatabase.Pubsub.RabbitMQ' started with 'Elixir.HVACDatabase.Pubsub.RabbitMQ':start_link() at <0.436.0> exit with reason {shutdown,{gen_server,call,[<0.463.0>,{call,{'exchange.declare',0,nil,<<"topic">>,false,true,false,false,false,[]},none,<0.436.0>},70000]}} in context child_terminated
2021-06-22 09:19:37.329 [error] <0.465.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.465.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:19:37.336 [error] <0.475.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.475.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.475.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:19:37.345 [error] <0.483.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.483.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.483.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:19:37.346 [error] <0.388.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: bad argument in call to erlang:send_after(nil, <0.483.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21 in application_master:init/4 line 142
2021-06-22 09:19:37.354 [error] <0.497.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.497.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2021-06-22 09:50:29.860 [error] <0.420.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.420.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.420.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:50:29.870 [error] <0.428.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.428.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.428.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:50:29.877 [error] <0.430.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.430.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.430.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:50:29.885 [error] <0.432.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.432.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.432.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:50:29.893 [error] <0.434.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.434.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.434.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21
2021-06-22 09:50:29.893 [error] <0.407.0>@Elixir.HVACClient.Devices.Device:init:21 CRASH REPORT Process <0.407.0> with 0 neighbours exited with reason: bad argument in call to erlang:send_after(nil, <0.434.0>, publish) in 'Elixir.HVACClient.Devices.Device':init/1 line 21 in application_master:init/4 line 142
2021-06-22 09:53:13.795 [error] <0.414.0>@Elixir.HVACClient.Devices.Device:schedule:29 CRASH REPORT Process <0.414.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.414.0>, publish) in 'Elixir.HVACClient.Devices.Device':schedule/0 line 29
2021-06-22 09:53:13.804 [error] <0.426.0>@Elixir.HVACClient.Devices.Device:schedule:29 CRASH REPORT Process <0.426.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.426.0>, publish) in 'Elixir.HVACClient.Devices.Device':schedule/0 line 29
2021-06-22 09:53:13.813 [error] <0.428.0>@Elixir.HVACClient.Devices.Device:schedule:29 CRASH REPORT Process <0.428.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.428.0>, publish) in 'Elixir.HVACClient.Devices.Device':schedule/0 line 29
2021-06-22 09:53:13.821 [error] <0.430.0>@Elixir.HVACClient.Devices.Device:schedule:29 CRASH REPORT Process <0.430.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.430.0>, publish) in 'Elixir.HVACClient.Devices.Device':schedule/0 line 29
2021-06-22 09:53:13.829 [error] <0.432.0>@Elixir.HVACClient.Devices.Device:schedule:29 CRASH REPORT Process <0.432.0> with 0 neighbours crashed with reason: bad argument in call to erlang:send_after(nil, <0.432.0>, publish) in 'Elixir.HVACClient.Devices.Device':schedule/0 line 29
2021-06-22 09:53:13.829 [error] <0.405.0>@Elixir.HVACClient.Devices.Device:schedule:29 CRASH REPORT Process <0.405.0> with 0 neighbours exited with reason: bad argument in call to erlang:send_after(nil, <0.432.0>, publish) in 'Elixir.HVACClient.Devices.Device':schedule/0 line 29 in application_master:init/4 line 142
2021-06-22 10:02:46.934 [error] <0.431.0> Supervisor 'Elixir.HVACServer.Supervisor' had child 'Elixir.HVACServer.ReadingsIngestor' started with 'Elixir.HVACServer.ReadingsIngestor':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.HVACServer.ReadingsIngestor',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,...}]}} in context start_error
2021-06-22 10:02:46.935 [error] <0.429.0> CRASH REPORT Process <0.429.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACServer.ReadingsIngestor',{'EXIT',{undef,[{'Elixir.HVACServer.ReadingsIngestor',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,...},...]}}}},...} in application_master:init/4 line 142
2021-06-22 10:03:20.071 [error] <0.449.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_2' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.071 [error] <0.447.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_0' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.071 [error] <0.453.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_3' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.071 [error] <0.454.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_4' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.071 [error] <0.448.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_1' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.085 [error] <0.466.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_7' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.085 [error] <0.459.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_5' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.095 [error] <0.487.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_10' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.095 [error] <0.460.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_6' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.095 [error] <0.468.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_8' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.096 [error] <0.511.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_16' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.447.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_0' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.448.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_1' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.454.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_4' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.453.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_3' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.487.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_10' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.468.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_8' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.466.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_7' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.106 [error] <0.449.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_2' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.107 [error] <0.460.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_6' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.107 [error] <0.511.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_16' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.107 [error] <0.459.0> CRASH REPORT Process 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_5' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:03:20.107 [error] <0.526.0> gen_server 'Elixir.HVACServer.ReadingsIngestor.Broadway.Producer_20' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"unexpected error when connecting to RabbitMQ broker">>} in 'Elixir.BroadwayRabbitMQ.Producer':handle_connection_failure/2 line 605
2021-06-22 10:16:38.984 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"could not checkout the connection owned by #PID<0.527.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 2729ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available a...">>,...} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 760
2021-06-22 10:16:40.974 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"could not checkout the connection owned by #PID<0.542.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 1986ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available a...">>,...} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 760
2021-06-22 10:16:42.970 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"could not checkout the connection owned by #PID<0.544.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 1994ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available a...">>,...} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 760
2021-06-22 10:16:44.974 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"could not checkout the connection owned by #PID<0.546.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 1999ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available a...">>,...} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 760
2021-06-22 10:16:46.973 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"could not checkout the connection owned by #PID<0.548.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 1995ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available a...">>,...} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 760
2021-06-23 07:30:54.612 [error] <0.449.0> Supervisor 'Elixir.HVACServer.Supervisor' had child 'Elixir.HVACServer.ReadingsIngestor' started with 'Elixir.HVACServer.ReadingsIngestor':start_link([]) at undefined exit with reason {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid configuration given to Broadway.start_link/2, unknown options [:on_failure], valid options are: [:module, :stages, :concurrency, :transformer, :spawn_opt, :hibernate_after, :rate_limiting]">>},[{'Elixir.Broadway',start_link,2,[{file,"lib/broadway.ex"},{line,919}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},...]}} in context start_error
2021-06-23 07:30:54.612 [error] <0.447.0> CRASH REPORT Process <0.447.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.HVACServer.ReadingsIngestor',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid configuration given to Broadway.start_link/2, unknown options [:on_failure], valid options are: [:module, :stages, :concurrency, :transformer, :spawn_opt, :hibernate_after, :rate_limiting]">>},[{'Elixir.Broadway',start_link,2,[{file,"lib/broadway.ex"},{line,919}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},...]}}}},...} in application_master:init/4 line 142
